### ISSUE TITLE
Links to/from subdirs broken depending on use_directory_urls 

### ISSUE THREAD

**Issue by PaulJacobs-percona** [orzih/mkdocs-with-pdf#10]
Version 0.3.3 + MkDocs 1.1.2
Link to sections from subdirs aren't connected depending on the value of `use_directory_urls`:

huh.md:
```
# TEST
## One
- [Link 1: to subdir (file)](subdir/huh.md)
- [Link 2: to subdir (section)](subdir/huh.md#one)
```

subdir/huh.md:
```
# SUBDIR TEST
# One
- [Link 3: to parent (file)](../huh.md)
- [Link 4: to parent (section)](../huh.md#one)
```

- `use_directory_urls: true` (default): Links 2 & 4 ok, 1 & 3 broken ('The application can’t be opened.')
- `use_directory_urls: false`: Links 1, 2 & 3 ok. Link 4 inactive.

**Comment by orzih** [comment]
Thanks.

I fixed generation methods of links in v0.4.0.
Please try it.

**Comment by PaulJacobs-percona** [comment]
Thank you. That is indeed fixed but not for all cases of nav hierarchies. For example:

```
nav:
   - top level:
      - second level:
         - huh.md
```

(see https://www.mkdocs.org/user-guide/writing-your-docs/#configure-pages-and-navigation)

This fails to build `AttributeError: 'Section' object has no attribute 'url'`.

I know my workaround is to avoid using dummy levels like this (even though MkDocs say "You may nest sections as deeply as you like") but they are useful for organising large sites or attempting to reproduce a structure built by another doc framework (which is my case).
Thanks.

**Comment by PaulJacobs-percona** [comment]
Resolved, thank you.
