### ISSUE TITLE
when with-pdf is enabled, mkdocs site's search box is gone

### ISSUE THREAD

**Issue by tbswork1** [orzih/mkdocs-with-pdf#125]
when I remove with-pdf, the search box is back again.

**Comment by anb0s** [comment]
adding plugin: with-pdf section removes implicit defined search plugin
```
plugins:
  with-pdf:
```

always define the search plugin explicitly
```
plugins:
  search:
    indexing: 'full'
```

**Comment by anb0s** [comment]
Note: If you have no plugins entry in your config file yet, you'll likely also want to add the search plugin. MkDocs enables it by default if there is no plugins entry set, but now you have to enable it explicitly.

**Comment by tbswork1** [comment]
It works. Thanks.
