### ISSUE TITLE
Alignment issue on Material info boxes

### ISSUE THREAD

**Issue by theblacknight** [orzih/mkdocs-with-pdf#135]
Theme: Material

I have an info box that is defined like this:

```
!!! info
    Info box content goes here.
```

However the icon doesn't render correctly in the pdf:

![image](https://user-images.githubusercontent.com/1329417/201069726-d2ec6af3-aa23-4a89-9078-b5b9d6209589.png)

It renders fine in the generated website:

![image](https://user-images.githubusercontent.com/1329417/201070141-386a00a0-5b40-4b20-a05c-9f4e4d6c7689.png)

The debug HTML looks like this:

```
<div class="admonition info">
<p class="admonition-title">Info</p>
<p>Info box content goes here.</p>
</div>

```

Any help debugging this would be appreciated. Nothing jumped out looking through the plugin css/scss files.

**Comment by santaimpersonator** [comment]
Seems like a duplicate issue of #89. You should probably close this issue and follow the existing issue.

* @cmaurer posted a solution
* I added to it, with what worked for me
