### ISSUE TITLE
Align left for images has no effects

### ISSUE THREAD

**Issue by JanoschDeurer** [orzih/mkdocs-with-pdf#14]
Mkdocs material supports image alignment: https://squidfunk.github.io/mkdocs-material/reference/images/#images
However, this has no effect on the pdf. I looked into the html debug output and the html attribute is set correctly. So I think there is either a problem with the css or with WeasyPrint.

If you give me a pointer on where to look I'll gladly help fixing the issue.

**Comment by orzih** [comment]
Thank you for your reporting.

WeasyPrint is not supported `img[align]` attribute.
So, I tried to convert it to CSS float style.
Please try it.

**Comment by MalkmusT** [comment]
I can confirm that this problem is solved in the latest verison v0.6.1
