### ISSUE TITLE
Links on second level toc items aren't working

### ISSUE THREAD

**Issue by JanoschDeurer** [orzih/mkdocs-with-pdf#15]
I'm using material for mkdocs. There are two different behaviors. If I don't set a first level heading for a page, mkdocs automatically renders the one that is given by the `nav` entry in the config file. In this case mkdocs-with-pdf throws the following error:
```
ERROR   -  Content discarded: target points to undefined anchor "('string', '#')"
```
The entry in the toc then points to `#`.

If I set the heading on the page manually by adding
```
# exampleHeading
```
to my markdown file I get the following error instead:
```
ERROR   -  No anchor #example/path/:exampleheading for internal URI reference
```
The resulting toc entry is then no longer a link meaning it is not clickable.

**Comment by JanoschDeurer** [comment]
After looking at this a bit closer there seems to be a general problem with all links towards level two headings.

**Comment by orzih** [comment]
Thank you for your report.

I added the `id` to first top level heading where it was missing.
Please check it.

**Comment by MalkmusT** [comment]
Most of our links for second level toc entries are working now.
We are still facing some failling links due to encoding issues, which is part of  a separate Issue.

**Comment by orzih** [comment]
Thank you for the confirmation work.

> We are still facing some failling links due to encoding issues, which is part of a separate Issue.

Could you provide a "mkdocs project" that this problem occurs?

**Comment by JanoschDeurer** [comment]
I dug a little deeper and the remaining problem is indeed with the encoding of special characters. I'm gonna open another ticket with a minimal project setup to repoduce and close this one :) Thansk for fixing this so fast :)
