### ISSUE TITLE
Admonition rendering

### ISSUE THREAD

**Issue by scampion** [orzih/mkdocs-with-pdf#18]
Dear All, 
Do you think it's possible to change the default rendering for admonition ? 
![image](https://user-images.githubusercontent.com/554155/93475060-782cc800-f8f8-11ea-90a4-c658089950f7.png)

I prefer the `read the doc` theme ;) 

![image](https://user-images.githubusercontent.com/554155/93475121-8bd82e80-f8f8-11ea-845d-697df45fcd53.png)

**Comment by JanoschDeurer** [comment]
I don't know if that is exactly what you want, but if you use  [mkdocs-material](https://squidfunk.github.io/mkdocs-material/) for your wiki you get the material design admonitions like here:
https://squidfunk.github.io/mkdocs-material/reference/admonitions/#supported-types

They are supported by mkdocs-with-pdf.

**Comment by scampion** [comment]
Hi @JanoschDeurer , thanks for the tip. 
Indeed, as in my previous comment, it's not perfect with the readthedoc theme but with material no problem. 
I propose to close this issues. 
Thanks for this great job.
