### ISSUE TITLE
Code block new line ignored 

### ISSUE THREAD

**Issue by scampion** [orzih/mkdocs-with-pdf#19]
Code block are rendered with oneline 
![image](https://user-images.githubusercontent.com/554155/93475266-b5915580-f8f8-11ea-883f-5d701b6b2f8d.png)

Instead of : 

![image](https://user-images.githubusercontent.com/554155/93475322-c215ae00-f8f8-11ea-9c67-6ce6361f30b4.png)

**Comment by JanoschDeurer** [comment]
Multiline code-blocks seem to work fine for me, can you provide the source code of the above code block?

**Comment by scampion** [comment]
Let me know if it's not enough

**Comment by scampion** [comment]
@JanoschDeurer with the material theme it's working 
I propose to close that issue

**Comment by canerbulduk** [comment]
I'm having the same issue, the code blocks are fine on website but the pdf is rendered as same as the first post of this issue.
 
It's rendered fine if I use material theme but I want to keep using readthedocs theme. ( It is not a supported theme, but I'm getting the best result with this theme at the moment.)

Do you think is it possible to fix this issue by adding few lines to pdf-print.css ? If yes, any suggestions?

**Comment by thomasboni** [comment]
I am experiencing the same issue with `readthedocs` theme, as described by @canerbulduk

**Comment by thomasboni** [comment]
Hello @canerbulduk @scampion @JanoschDeurer I don't know if it's still useful for you but I found a workaround to display new lines in code blocks of PDF output when using `readthedocs` theme:

I specify a css extra file in my `mkdocs.yml`: 

```css
# Theme configuration      
theme:                     
  name: 'readthedocs'      
  highlightjs: true        
  hljs_languages:          
      - yaml               
  locale: en               
  titles_only: false       
  collapse_navigation: true
extra_css:                 
    - css/extra.css                        
```

In my css file (`docs/css/extra.css`): 

```css
code.hljs {            
  display: block;      
  white-space: pre-wrap
}                      
```

And then, code blocks are well displayed in my PDF output :)
