### ISSUE TITLE
All images removed from document

### ISSUE THREAD

**Issue by binnes** [orzih/mkdocs-with-pdf#2]
Commit ae134330a479c7697aff35a704b1927cd5cb3d47 added _remove_empty_tags functionality, but I think this results in all <p><img ...../></p> tags being removed from the generated pdf files.

p is in the includes array and a paragraph only containing an image tag has no text in it, so 'if x.name in includes and len(x.get_text(strip=True)) == 0:' at line 109 of generator.py returns true causing the tag to be removed

If I comment out the call to the _remove_empty_tags function the images appear in the generated pdf, if I leave the call in I get no images in the pdf

**Comment by orzih** [comment]
Thank you for your advice.

This commit meaning, these tags(p: mkdocs style, article: material style) are root tags for each page generated by mkdocs, and empty tag will generate a blank page.

If they has image, I changed it to exclude it.

**Comment by binnes** [comment]
Fixed in release https://github.com/orzih/mkdocs-with-pdf/releases/tag/v0.2.4
