### ISSUE TITLE
Provide some option to fail on errors

### ISSUE THREAD

**Issue by JanoschDeurer** [orzih/mkdocs-with-pdf#24]
Mkdocs provides a `--strict` flag for the build with
```
mkdocs build --strict
```
This fails on all warnings. This is especially useful for pipelines, where you don't want to publish when there are warnings or errors. However when enabled it ignores all errors from mkdocs-with-pdf. It would be great to either directly integrate with the mkdocs flag or to provide a different way to configure mkdocs-with-pdf to fail on errors.

**Comment by orzih** [comment]
Simply, this plugin will throw an exception if an error or warning occurs when mkdocs is run with the restriction options, in v0.7.5.

**Comment by JanoschDeurer** [comment]
Thanks again :) The output now shows the back trace, which is not optimal, but I don't see any other option in the mkdocs plugin system either.
