### ISSUE TITLE
How to add image/logo to cover page

### ISSUE THREAD

**Issue by PaulJacobs-percona** [orzih/mkdocs-with-pdf#28]
I've managed to produce a nice-looking PDF matching our corp ident but can't see how to add an image (Logo) to the cover. Is it possible?

**Comment by orzih** [comment]
Not yet supported.

**Comment by orzih** [comment]
Added the `cover_logo` option in release v0.8.0.
Please check it.

**Comment by PaulJacobs-percona** [comment]
> Added the `cover_logo` option in release v0.8.0.
> Please check it.

Works great. Thanks.
