### ISSUE TITLE
Document links don't work in pdf

### ISSUE THREAD

**Issue by binnes** [orzih/mkdocs-with-pdf#3]
If I include a link to another page in the Markdown using `[link description](page.md)` syntax the link doesn't not work in the generated PDF - the generated web site works OK.  

There is an error output when the **mkdocs build** command is run, that corresponds to each instance of a page link in the Markdown docs : **ERROR   -  No anchor #page.html: for internal URI reference**.

It doesn't matter if the Markdown pages are in the same directory, in the root docs directory or in a subdirectories of the docs directory - none of the internal links work.

I have the recommended **toc** extension with the **permalink: true** option set and the **use_directory_urls** option set to **false** as specified in the documentation.

Using the **debug_html** option I can see there is no **id** attribute on the article tag for a page, so looks like there is no anchor being created for pages, just a **data-url** tag.

**Comment by orzih** [comment]
Thank you for your report.

I fixed this bug.
Could you try it in your case?

**Comment by binnes** [comment]
Thanks for fixing, all working now

**Comment by binnes** [comment]
Just tested on another project and the No anchor messages are back - not investigated yet, but this could be the hanging : issue that was included in the PR?

If you want to see the Markdown that is generating the issue it is in this git repo : https://github.com/binnes/Node-RED-container-prod

**Comment by binnes** [comment]
Thanks for the quick fix, all pdf generation works now
