### ISSUE TITLE
PDF generation slows down iterative development via `mkdocs serve`

### ISSUE THREAD

**Issue by mikesamuel** [orzih/mkdocs-with-pdf#41]
PDF generation takes a while

```
$ time mkdocs build
...
INFO    -  Converting 14 articles to PDF took 28.5s
INFO    -  Documentation built in 30.59 seconds

real	0m32.552s
user	0m29.004s
sys	0m0.923s
```

so PDF generation takes about 90% of the total time for my particular build.

This is fine when running `mkdocs build`, but when using `mkdocs serve` this means that any edit to any file takes half a minute to show up.

Might it be possible to skip or background PDF generation during `mkdocs serve`?

**Comment by orzih** [comment]
You can use `enabled_if_env` option.

eg.
First, You add enabled_if_env in your `mkdocs.yml`:

```yaml
plugins:
    - with-pdf:
        enabled_if_env: ENABLE_PDF_EXPORT
```

on **"serve"**:

```sh
$ mkdocs serve
  ...
WARNING -  without generate PDF(set environment variable ENABLE_PDF_EXPORT to 1 to enable)
  ...
```

on **"build"**:

comment out this option, or run below:

```sh
$ ENABLE_PDF_EXPORT=1 mkdocs build
```

**Comment by mikesamuel** [comment]
Thanks.  Works like a charm.

Sorry I didn't recognize that under https://github.com/orzih/mkdocs-with-pdf#-and-more .  If you'd like I can send a PR to flesh out that section.

**Comment by orzih** [comment]
Thanks, yes please.
