### ISSUE TITLE
Config Tag where Download link gets appended to (Feature request)

### ISSUE THREAD

**Issue by tomw1808** [orzih/mkdocs-with-pdf#42]
Right now the download link get's appended to md-footer-copyright in the material design and always has "... download PDF".

I might be alone with this issue, but it would be very helpful if the tag for the download link would be available via the config parameters.

https://github.com/orzih/mkdocs-with-pdf/blob/53c1e826f43de69236e1042e4bc8c73535901413/mkdocs_with_pdf/themes/material.py#L25

Also, it would be great if the Link-Text would be something that can be adjusted easily. 

Thank you for considering. If it doesn't fit your overall roadmap, please just close.

**Comment by orzih** [comment]
Added support programmable rendering hooks in v0.8.2.
Please try sample(`pdf_event_hook.py`) in [README](https://github.com/orzih/mkdocs-with-pdf#advanced-rendering-hooks-experimental).

**Comment by tomw1808** [comment]
LOVE IT!
Thank you!!!!
