### ISSUE TITLE
How to overwrite the scss for pdf.

### ISSUE THREAD

**Issue by kittiu** [orzih/mkdocs-with-pdf#48]
Hi, I have read the documentation. And it seem the way to change is to add our file to `extra_css` in config file.

```
extra_css:
    - css/extra.css
```

I have done so. On build, the file extra.css wll be addded in `site` but nothing seem to happen

**Comment by orzih** [comment]
`extra_css` is mkdocs's option(pure **css** file - not _SCSS/SASS_).
see [material sample `extra.css`](https://github.com/orzih/mkdocs-with-pdf/blob/master/samples/mkdocs-material/docs/assets/css/extra.css).

Please check `debug_html` option of this plugin.
...and browse output with chrome [Chrome Print Preview Mode](https://developers.google.com/web/tools/chrome-devtools/css/print-preview) will you help.

Note: `WeasyPrint` and `Google Chrome` are not fully compatible.

**Comment by kittiu** [comment]
Thank you @orzih and also thank you for excellent work also.
