### ISSUE TITLE
Fonts : Headers remplaced by squares

### ISSUE THREAD

**Issue by Tomaaso** [orzih/mkdocs-with-pdf#65]
![image](https://user-images.githubusercontent.com/47305575/121537093-eb84e580-ca03-11eb-8e70-b225a266a1d1.png)

![image](https://user-images.githubusercontent.com/47305575/121538274-f55b1880-ca04-11eb-931e-6160ff6186b5.png)

Hi, I have a problem with headers fonts but impossible for me to fix it... This screeshot is from the sample mkdocs. 

[debug.txt](https://github.com/orzih/mkdocs-with-pdf/files/6632659/debug.txt)

Thanks.

**Comment by orzih** [comment]
Hi @Wikhar.

It seems that the `sans-serif` font is not configured on your system.

See:
+ https://weasyprint.readthedocs.io/en/latest/features.html#fonts
+ https://stackoverflow.com/questions/47749526/how-to-use-custom-font-with-weasyprint

---

If you simply use `serif` font, add the following to your css:
```css
@media print {
  h1, h2, h3, h4, h5, h6, label { font-family: serif !important; }
}
```
