### ISSUE TITLE
Exclude index.md 

### ISSUE THREAD

**Issue by fernwerker** [orzih/mkdocs-with-pdf#73]
Is there any way to exclude the index.md from pdf generation?
My home always goes to a "blog"-similar entry, which is not supposed to be genreated in the pdf file.

Any ideas?
I tried:
```
      exclude_pages:
        - .
        - index.md
        - /
```
No success so far.

**Comment by orzih** [comment]
See https://github.com/orzih/mkdocs-with-pdf/issues/69#issuecomment-889342144, same issue.

**Comment by fernwerker** [comment]
Unfortunately this does not work. So index is still included to the pdf.

But I just moved the blog posts to a sub-page and added something generic to index.. so visitors won't arrive at posts, but so what. :D
