### ISSUE TITLE
Internal refs broken when use_directory_urls=false AND file name != *index.md

### ISSUE THREAD

**Issue by PaulJacobs-percona** [orzih/mkdocs-with-pdf#8]
Internal links in PDF inactive when `use_directory_urls` is false and filename does not begin with `index`.

Example:

```md
# TEST PAGE
- [Internal link to one](#one)
- [Internal link to two](#two)
## One
One
## Two
two
```

- Links rendered correctly when file is named `index.md`, `indexnot.md`.
- Links appear but are inactive when file is named `notindex.md`, `not.md`.
- When `use_directory_links: true` (the default) all links are correct.

**Comment by orzih** [comment]
Thank you for your reporting, and fixed in new release v0.3.2.

**Comment by PaulJacobs-percona** [comment]
Thanks. It seems to be fixed but only for files in the root directory, not for subdirectories. 

To be clear, in my test:

```
docs/index.md - OK
docs/notindex.md - OK
docs/indexnot.md - OK (Fixed)
docs/not.md - OK (Fixed)
docs/subdir/index.md - OK
docs/subdir/notindex.md - OK
docs/subdir/indexnot.md - Links indicated but not working
docs/subdir/not.md - Links indicated but not working
```

**Comment by orzih** [comment]
Oh really.
I'll fix it soon.

**Comment by PaulJacobs-percona** [comment]
Great, all working now.
